"""Generate a standalone, human-readable Python script that reproduces a job's analysis with
plain Scanpy / PyDESeq2 calls and the exact parameters that were used."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent

SOURCE_FILES = ["app.py", "common.py", "io_utils.py", "geo.py", "bulk_pipeline.py", "sc_pipeline.py",
                "pseudobulk.py", "markers.py", "report.py", "codegen.py", "agent.py", "demo.py"]


def pipeline_sources() -> dict[str, str]:
    out = {}
    for f in SOURCE_FILES:
        p = ROOT / f
        if p.exists():
            out[f"server/{f}"] = p.read_text()
    web = ROOT.parent / "web" / "index.html"
    if web.exists():
        out["web/index.html"] = web.read_text()
    return out


def script_for_job(job_dir: Path) -> str:
    req = json.loads((job_dir / "request.json").read_text())
    res = json.loads((job_dir / "result.json").read_text()) if (job_dir / "result.json").exists() else {}
    params = {**req.get("params", {}), **(res.get("params") or {})}
    inp = (job_dir / "input").resolve()
    files = []
    for f in req.get("files", []):
        pf = Path(f).resolve()
        try:
            rel = pf.relative_to(inp).as_posix()   # keeps sub-folders from unpacked archives
        except ValueError:
            rel = pf.name
        if not rel.lower().endswith((".tar", ".tar.gz", ".tgz", ".zip")) and "readme" not in rel.lower():
            files.append(rel)
    if req["kind"] == "bulk" and (job_dir / "metadata_used.csv").exists():
        files = files + ["metadata_used.csv"]
    if req["kind"] == "sc" and (job_dir / "sample_metadata.csv").exists():
        files = files + ["sample_metadata.csv"]
    return (bulk_script if req["kind"] == "bulk" else sc_script)(files, params, res)


def _hdr(title, files):
    return f'''#!/usr/bin/env python3
"""{title}

Generated by RNAseq Bench. This is a plain, dependency-light script that reproduces the
analysis with the same parameters; edit freely. Run it from this job's "input" folder (download it
from the Files list) or from any folder containing the input files:
    {', '.join(files[:12])}{' …' if len(files) > 12 else ''}
Requirements: scanpy, anndata, pandas, numpy, matplotlib, seaborn, pydeseq2 (and harmonypy, leidenalg for single-cell).
"""
import re, warnings
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")
'''


def bulk_script(files, P, res):
    counts = next((f for f in files if not ("meta" in f.lower() or "series_matrix" in f.lower())), files[0] if files else "counts.csv")
    meta = next((f for f in files if "meta" in f.lower() or "sample" in f.lower() or "coldata" in f.lower()), None)
    factor = P.get("factor", "condition"); ref = P.get("reference", "control"); alt = P.get("alternative", "treated")
    covars = P.get("covariates") or []
    design = "~" + " + ".join(covars + [factor])
    alpha = P.get("alpha", 0.05); lfc = P.get("lfc", 1.0)
    s = _hdr(f"Bulk RNA-seq: {alt} vs {ref} (DESeq2)", files)
    s += f'''
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats
from pydeseq2.default_inference import DefaultInference
import seaborn as sns

# ------------------------------------------------------------------ 1. load counts
sep = "\\t" if "{counts}".endswith((".tsv", ".txt", ".tsv.gz", ".txt.gz")) else ","
counts = pd.read_csv("{counts}", sep=sep, index_col=0)
counts = counts.select_dtypes("number").drop(columns=[c for c in ("Length", "Chr", "Start", "End", "Strand") if c in counts], errors="ignore")
counts = counts.fillna(0).round().astype(int).clip(lower=0)
counts = counts[~counts.index.duplicated()]

# technical replicates (names differing only by a trailing rep/pt index) are summed per library
stem = [re.sub(r"[_\\-. ]?(rep|r|pt|lane|l|tech|t)\\d+$", "", c, flags=re.I) for c in counts.columns]
if len(set(stem)) < len(stem) and {P.get("collapse_replicates", "auto")!r} != False:
    counts = counts.T.groupby(stem, sort=False).sum().T

# ------------------------------------------------------------------ 2. sample metadata
'''
    if meta:
        s += f'meta = pd.read_csv("{meta}", index_col=0).loc[counts.columns]\n'
    else:
        s += f'''# The app exported the sample sheet it used (GEO series matrix + inferred sex etc.) as metadata_used.csv —
# download it from the results page and keep it next to this script.
meta = pd.read_csv("metadata_used.csv", index_col=0)
meta.index = meta.index.astype(str)
common = [c for c in counts.columns if c in meta.index]     # samples the app used (others were dropped: no metadata / missing factor)
counts, meta = counts[common], meta.loc[common]
counts = counts[[c for c in counts.columns if c in meta.index]]
meta = meta.loc[counts.columns]
# groups used in the app: {res.get("params", {}).get("levels", {}).get(factor, [])}
'''
    s += f'''meta = meta.replace({{"": np.nan, "NA": np.nan, "nan": np.nan, "None": np.nan}}).dropna(axis=1, how="all")
for c in meta.columns:
    if pd.to_numeric(meta[c], errors="coerce").notna().all() and meta[c].nunique() > 5:
        meta[c] = pd.to_numeric(meta[c])          # continuous covariate
    else:
        meta[c] = meta[c].astype("string")

# ------------------------------------------------------------------ 3. DESeq2
factor, ref, alt = "{factor}", "{ref}", "{alt}"
design = "{design}"
meta = meta[meta[factor].notna()]                      # samples without a value for the factor are left out
counts = counts[meta.index]
for c in meta.columns:
    if str(meta[c].dtype) == "string":
        meta[c] = meta[c].fillna("unknown").astype(str)   # NaN in any column would make formulaic drop the sample
min_n = int(meta[factor].value_counts().min())
cf = counts[(counts >= 10).sum(axis=1) >= min_n]
inference = DefaultInference(n_cpus=4)
meta[factor] = pd.Categorical(meta[factor], categories=[ref] + [l for l in meta[factor].unique() if l != ref])  # ref = baseline
dds = DeseqDataSet(counts=cf.T, metadata=meta, design=design, refit_cooks=True, inference=inference, quiet=True)
dds.deseq2()
ds = DeseqStats(dds, contrast=[factor, alt, ref], alpha={alpha}, inference=inference, quiet=True)
ds.summary()
res = ds.results_df.copy()
coeff = next(c for c in dds.varm["LFC"].columns if factor in c and alt in c)
ds.lfc_shrink(coeff=coeff)
res["log2FC_shrunk"] = ds.results_df["log2FoldChange"]
res.sort_values("pvalue").to_csv("deseq2_results.csv")
sig = res[(res.padj < {alpha}) & (res.log2FoldChange.abs() >= {lfc})]
print(f"{{(sig.log2FoldChange > 0).sum()}} up, {{(sig.log2FoldChange < 0).sum()}} down ({{alt}} vs {{ref}}, padj<{alpha}, |log2FC|>={lfc})")

# ------------------------------------------------------------------ 4. VST, PCA, correlation
dds.vst(use_design=False)
vst = pd.DataFrame(dds.layers["vst_counts"], index=dds.obs_names, columns=dds.var_names).T
top = vst.loc[vst.var(axis=1).sort_values(ascending=False).index[:500]]
U, sv, _ = np.linalg.svd((top.T - top.T.mean()).values, full_matrices=False)
pcs, pvar = U * sv, sv**2 / (sv**2).sum()
fig, ax = plt.subplots(figsize=(5.5, 4.5))
for lvl, col in zip(meta[factor].unique(), ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"]):
    m = (meta[factor] == lvl).values
    ax.scatter(pcs[m, 0], pcs[m, 1], c=col, s=60, label=lvl, edgecolor="white")
ax.set_xlabel(f"PC1 ({{100*pvar[0]:.1f}}%)"); ax.set_ylabel(f"PC2 ({{100*pvar[1]:.1f}}%)"); ax.legend()
fig.savefig("pca.png", dpi=200, bbox_inches="tight")
sns.clustermap(vst.corr(), cmap="viridis").savefig("correlation.png", dpi=200)

# ------------------------------------------------------------------ 5. volcano
r = res.dropna(subset=["pvalue"]).copy(); r["nlp"] = -np.log10(r.pvalue.clip(lower=1e-300))
s = (r.padj < {alpha}) & (r.log2FoldChange.abs() >= {lfc})
fig, ax = plt.subplots(figsize=(7, 5))
ax.scatter(r.log2FoldChange[~s], r.nlp[~s], s=3, c="#c7ccd1", alpha=.5)
ax.scatter(r.log2FoldChange[s], r.nlp[s], s=7, c=np.where(r.log2FoldChange[s] > 0, "#c9304f", "#2a64b0"))
for g, row in r[s].nsmallest(15, "pvalue").iterrows():
    ax.annotate(g, (row.log2FoldChange, row.nlp), fontsize=7, xytext=(3, 2), textcoords="offset points")
ax.set_xlabel(f"log2 fold change ({{alt}} / {{ref}})"); ax.set_ylabel("-log10 p")
fig.savefig("volcano.png", dpi=200, bbox_inches="tight")

# ------------------------------------------------------------------ 6. heatmap of top genes
hm = vst.loc[sig.nsmallest(50, "padj").index, meta.sort_values(factor).index]
sns.clustermap(hm, z_score=0, cmap="RdBu_r", center=0, col_cluster=False, figsize=(8, 10)).savefig("heatmap.png", dpi=200)
'''
    s += bulk_addons(P, res)
    s += '\nprint("done — results and figures are in this folder")\n'
    return s


def sc_script(files, P, res):
    main = files[0] if files else "counts.h5ad"
    res_ = P.get("resolution", 0.5); n_hvg = P.get("n_hvg", 2000)
    batch = P.get("batch_key") or ""
    pb = (res.get("pseudobulk") or {}) if isinstance(res.get("pseudobulk"), dict) else {}
    s = _hdr("Single-cell RNA-seq: QC, clustering, markers, pseudobulk (Scanpy)", files)
    s += f'''
import scanpy as sc
sc.settings.verbosity = 1

# ------------------------------------------------------------------ 1. load
# One reader per input format; several files (one per sample, e.g. GSM-prefixed 10x triplets from a
# GEO RAW.tar) are stacked with the file prefix stored in obs["sample"].
import glob, gzip, re, scipy.io, scipy.sparse as sp

def read_one(path):
    p = path.lower()
    if p.endswith(".h5ad"):
        return sc.read_h5ad(path)
    if p.endswith(".h5"):
        return sc.read_10x_h5(path)
    if p.endswith((".mtx", ".mtx.gz")):
        stem = re.sub(r"[_\\-.]?matrix\\.mtx(\\.gz)?$", "", path, flags=re.I)
        feat = next(f for f in glob.glob(stem + "*") if re.search(r"(features|genes)\\.tsv", f))
        bcs = next(f for f in glob.glob(stem + "*") if "barcodes" in f)
        m = scipy.io.mmread(path)
        ft = pd.read_csv(feat, sep="\t", header=None, dtype=str); bc = pd.read_csv(bcs, sep="\t", header=None, dtype=str)[0]
        a = sc.AnnData(sp.csr_matrix(m.T), obs=pd.DataFrame(index=bc.values), var=pd.DataFrame(index=ft[1 if ft.shape[1] > 1 else 0].values))
        if ft.shape[1] >= 3:
            a = a[:, ft[2].str.contains("Gene Expression").values].copy()
        return a
    return sc.read_csv(path, delimiter="\\t" if p.endswith((".txt", ".tsv", ".txt.gz", ".tsv.gz")) else ",").T

FILES = {files!r}
parts = []
for f in FILES:
    if re.search(r"(features|genes|barcodes)\\.tsv|series_matrix|meta", f, re.I):
        continue
    a = read_one(f); a.var_names_make_unique()
    name = re.sub(r"[_\\-.]?(matrix\\.mtx|filtered_feature_bc_matrix|counts?)?(\\.\\w+)*$", "", f.split("/")[-1])
    if not name:   # bare matrix.mtx.gz inside a per-sample folder: use the first informative folder name
        name = next((d for d in reversed(f.split("/")[:-1]) if not re.search(r"feature_bc_matrix|_untar|^outs$|^input$", d)), "sample")
    a.obs["sample"] = name
    parts.append(a)
adata = parts[0] if len(parts) == 1 else sc.concat(parts, join="outer", index_unique="-", fill_value=0)
import os
if os.path.exists("sample_metadata.csv"):   # exported by the app: sample -> condition/genotype/… (from the GEO series matrix)
    smeta = pd.read_csv("sample_metadata.csv", index_col=0, dtype=str)
    for c in smeta.columns:
        adata.obs[c] = adata.obs["sample"].map(smeta[c]).astype(str).values
adata.var_names_make_unique(); adata.obs_names_make_unique()
# If gene ids are Ensembl accessions, map them to symbols first (adata.var_names = symbols).

# ------------------------------------------------------------------ 2. QC (MAD-based thresholds as in Heumos et al. 2023)
adata.var["mt"] = adata.var_names.str.upper().str.startswith("MT-")
adata.var["ribo"] = adata.var_names.str.upper().str.match(r"^RP[SL]\\d")
sc.pp.calculate_qc_metrics(adata, qc_vars=["mt", "ribo"], percent_top=[20], log1p=True, inplace=True)
def mad(x): return np.median(np.abs(x - np.median(x))) * 1.4826
lg = adata.obs["log1p_n_genes_by_counts"].values; mt = adata.obs["pct_counts_mt"].values
min_genes, max_genes = {P.get("min_genes", "max(100, int(np.expm1(np.median(lg) - 5*mad(lg))))")}, {P.get("max_genes", "int(np.expm1(np.median(lg) + 5*mad(lg)))")}
max_mt = {P.get("max_mt", "float(np.clip(np.median(mt) + 3*mad(mt), 5, 25))")}
adata = adata[(adata.obs.n_genes_by_counts >= min_genes) & (adata.obs.n_genes_by_counts <= max_genes) & (adata.obs.pct_counts_mt <= max_mt)].copy()
sc.pp.filter_genes(adata, min_cells={P.get("min_cells", 3)})
print(adata)
'''
    if P.get("doublets") is True:
        s += f'''
# ------------------------------------------------------------------ 3. doublets
sc.pp.scrublet(adata{", batch_key=" + repr(batch) if batch else ""}, random_state=0)
adata = adata[~adata.obs.predicted_doublet].copy()
'''
    s += f'''
# ------------------------------------------------------------------ 4. normalize, HVG, PCA
adata.layers["counts"] = adata.X.copy()
sc.pp.normalize_total(adata, target_sum=1e4); sc.pp.log1p(adata)
adata.layers["log1p"] = adata.X.copy()
sc.pp.highly_variable_genes(adata, n_top_genes={n_hvg}, flavor="seurat_v3", layer="counts"{", batch_key=" + repr(batch) if batch else ""})
ad_h = adata[:, adata.var.highly_variable].copy()
sc.pp.scale(ad_h, max_value=10)
sc.tl.pca(ad_h, n_comps=50, svd_solver="arpack", random_state=0)
adata.obsm["X_pca"] = ad_h.obsm["X_pca"]
rep = "X_pca"
'''
    if batch and P.get("integrate", True):
        s += f'''
# ------------------------------------------------------------------ 5. Harmony batch integration over "{batch}"
import harmonypy
ho = harmonypy.run_harmony(adata.obsm["X_pca"], adata.obs, ["{batch}"], max_iter_harmony=20, random_state=0)
Z = np.asarray(ho.Z_corr); adata.obsm["X_pca_harmony"] = Z if Z.shape[0] == adata.n_obs else Z.T
rep = "X_pca_harmony"
'''
    s += f'''
# ------------------------------------------------------------------ 6. graph, UMAP, Leiden, markers
sc.pp.neighbors(adata, n_neighbors=15, n_pcs={P.get("n_pcs") or 30}, use_rep=rep, random_state=0)
sc.tl.umap(adata, random_state=0)
sc.tl.leiden(adata, resolution={res_}, flavor="igraph", n_iterations=2, random_state=0)
sc.tl.rank_genes_groups(adata, "leiden", method="wilcoxon", layer="log1p", use_raw=False, pts=True)
sc.get.rank_genes_groups_df(adata, None).to_csv("markers.csv", index=False)
sc.pl.umap(adata, color="leiden", legend_loc="on data", show=False); plt.savefig("umap.png", dpi=200, bbox_inches="tight")
sc.pl.rank_genes_groups_dotplot(adata, n_genes=4, layer="log1p", use_raw=False, standard_scale="var", show=False); plt.savefig("dotplot.png", dpi=200, bbox_inches="tight")
# Annotate clusters by inspecting markers.csv / dotplot.png, then e.g.:
# adata.obs["cell_type"] = adata.obs.leiden.map({{"0": "CD4 T", "1": "CD14 Mono", ...}})
adata.write_h5ad("analyzed.h5ad", compression="gzip")
'''
    if pb.get("sample_key"):
        sk, ck, ref, alt = pb["sample_key"], pb["condition_key"], pb["reference"], pb["alternative"]
        cov = pb.get("covariates") or []
        s += f'''
# ------------------------------------------------------------------ 7. pseudobulk DESeq2: {alt} vs {ref}, samples = "{sk}"
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats
from pydeseq2.default_inference import DefaultInference
sample_key, cond = "{sk}", "{ck}"
smeta = adata.obs.groupby(sample_key, observed=True)[[cond{"".join(", " + repr(c) for c in cov)}]].first().astype(str)
C = adata.layers["counts"]
pb = pd.DataFrame(np.vstack([np.asarray(C[(adata.obs[sample_key] == s_).values].sum(0)).ravel() for s_ in smeta.index]),
                  index=smeta.index, columns=adata.var_names).round().astype(int)
pb = pb.loc[:, (pb >= 10).sum(0) >= 2]
inference = DefaultInference(n_cpus=4)
smeta[cond] = pd.Categorical(smeta[cond], categories=["{ref}"] + [l for l in smeta[cond].unique() if l != "{ref}"])
dds = DeseqDataSet(counts=pb, metadata=smeta, design="~{' + '.join(cov + [ck])}", refit_cooks=True, inference=inference, quiet=True)
dds.deseq2()
ds = DeseqStats(dds, contrast=[cond, "{alt}", "{ref}"], inference=inference, quiet=True); ds.summary()
ds.results_df.sort_values("pvalue").to_csv("pseudobulk_all_cells.csv")
# Repeat with C restricted to one cell type (adata.obs.cell_type == ...) for per-population tests.
# Composition: pd.crosstab(adata.obs[sample_key], adata.obs["cell_type"], normalize="index") then Mann-Whitney per column across samples.
'''
    s += sc_addons(P, res)
    s += '\nprint("done — results and figures are in this folder")\n'
    return s


# ------------------------------------------------------------------ expert add-ons
# Only the add-ons a job actually ran are written into its script, so the script stays a faithful
# record of that analysis rather than a menu of everything the app can do.

def _counter(start):
    c = [start - 1]

    def nxt():
        c[0] += 1
        return c[0]
    return nxt


def _goi(P):
    g = P.get("genes")
    if not g:
        return []
    return [x for x in re.split(r"[,\s;]+", str(g) if not isinstance(g, list) else ",".join(g)) if x]


def bulk_addons(P, res) -> str:
    s = ""
    n = _counter(7)          # the fixed part of the bulk script ends at step 6
    pr = res.get("params") or {}
    alt, ref = pr.get("alternative", "alt"), pr.get("reference", "ref")
    goi = _goi(P)
    if goi:
        s += f'''
# ------------------------------------------------------------------ {n()}. genes of interest
# Normalized counts per sample for the genes you asked about, whatever their significance.
goi = {goi!r}
norm = pd.DataFrame(dds.layers["normed_counts"], index=dds.obs_names, columns=dds.var_names).T
found = [g for g in goi if g in norm.index]
if found:
    d = norm.loc[found]
    fig, axs = plt.subplots(1, len(found), figsize=(2.3 * len(found), 3.2), squeeze=False)
    for ax, g in zip(axs[0], found):
        for i, lv in enumerate(meta[factor].unique()):
            y = d.loc[g, meta.index[meta[factor] == lv]]
            ax.scatter(np.random.normal(i, .06, len(y)), y, s=18)
        ax.set_xticks(range(meta[factor].nunique())); ax.set_xticklabels(meta[factor].unique(), rotation=30, fontsize=7)
        ax.set_title(g, fontsize=9); ax.set_ylabel("normalized counts" if g == found[0] else "")
    fig.tight_layout(); fig.savefig("genes_of_interest.png", dpi=200)
    res.loc[found].to_csv("genes_of_interest.csv")
'''
    if P.get("gsea", True):
        s += f'''
# ------------------------------------------------------------------ {n()}. GSEA (pre-ranked)
# Ranks every tested gene by the Wald statistic, then asks which gene sets pile up at either end.
# Unlike over-representation it uses no significance cut-off, so coordinated small changes still show.
import gseapy as gp
MOUSE = np.mean([bool(re.match(r"^[A-Z][a-z0-9]+$", g)) for g in res.index[:500]]) > .5   # symbol casing
rnk = res.dropna(subset=["stat"])["stat"].sort_values(ascending=False)
rnk.index = rnk.index.astype(str).str.upper() if MOUSE else rnk.index.astype(str)
rnk = rnk[~rnk.index.duplicated()]
rnk.to_csv("ranked_genes.rnk", sep="\\t", header=False)
# gene_sets accepts an Enrichr library name (downloads once) or a local .gmt path
pre = gp.prerank(rnk=rnk, gene_sets="MSigDB_Hallmark_2020", permutation_num=1000,
                 min_size=15, max_size=500, threads=4, seed=0, outdir=None, no_plot=True, verbose=False)
gsea_res = pre.res2d.copy()
for c in ("NES", "FDR q-val", "NOM p-val"):
    gsea_res[c] = pd.to_numeric(gsea_res[c], errors="coerce")
gsea_res.sort_values("FDR q-val").to_csv("gsea_results.csv", index=False)
top = gsea_res.reindex(gsea_res["NES"].abs().sort_values(ascending=False).index).head(14).iloc[::-1]
fig, ax = plt.subplots(figsize=(7, 5))
ax.barh(range(len(top)), top["NES"], color=["#c9304f" if v > 0 else "#2a64b0" for v in top["NES"]])
ax.set_yticks(range(len(top))); ax.set_yticklabels([t[:46] for t in top["Term"]], fontsize=7.5)
ax.axvline(0, color="#444", lw=.8); ax.set_xlabel("NES (positive = enriched in {alt})")
fig.tight_layout(); fig.savefig("gsea.png", dpi=200)
'''
    if P.get("activity", True):
        s += f'''
# ------------------------------------------------------------------ {n()}. pathway and TF activity (decoupler)
# Footprint methods: score a pathway from the genes it *responds* on (PROGENy) and a transcription
# factor from its known targets (CollecTRI), rather than from the expression of its own members.
import decoupler as dc
MOUSE = np.mean([bool(re.match(r"^[A-Z][a-z0-9]+$", g)) for g in res.index[:500]]) > .5
stat = res["stat"].dropna()
stat.index = stat.index.astype(str).str.upper() if MOUSE else stat.index.astype(str)
stat = stat[~stat.index.duplicated()]
mat = pd.DataFrame([stat.values], index=["{alt} vs {ref}"], columns=stat.index)
organism = "mouse" if MOUSE else "human"
progeny = dc.op.progeny(organism=organism, top=500)
collectri = dc.op.collectri(organism=organism)
for name, net, n_show in [("progeny", progeny, 14), ("collectri", collectri, 20)]:
    es, pv = dc.mt.ulm(data=mat, net=net, tmin=5)
    sc_ = es.iloc[0]
    sc_ = sc_.reindex(sc_.abs().sort_values(ascending=False).index).head(n_show).sort_values()
    fig, ax = plt.subplots(figsize=(5.8, .28 * len(sc_) + 1.4))
    ax.barh(range(len(sc_)), sc_.values, color=["#c9304f" if v > 0 else "#2a64b0" for v in sc_.values])
    ax.set_yticks(range(len(sc_))); ax.set_yticklabels(sc_.index, fontsize=8.5)
    ax.axvline(0, color="#444", lw=.8); ax.set_xlabel("activity (ULM t-value), positive = up in {alt}")
    fig.tight_layout(); fig.savefig(f"activity_{{name}}.png", dpi=200)
    es.T.to_csv(f"activity_{{name}}.csv")
'''
    return s


def sc_addons(P, res) -> str:
    s = ""
    n = _counter(8)          # the fixed part of the single-cell script ends at step 7
    goi = _goi(P)
    pb = (res.get("pseudobulk") or {}) if isinstance(res.get("pseudobulk"), dict) else {}

    if goi:
        s += f'''
# ------------------------------------------------------------------ {n()}. genes of interest
goi = [g for g in {goi!r} if g in adata.var_names]
if goi:
    sc.pl.umap(adata, color=goi, cmap="viridis", ncols=4, show=False, save="_genes_of_interest.png")
'''
    if P.get("celltypist"):
        s += f'''
# ------------------------------------------------------------------ {n()}. automated annotation (CellTypist)
# A reference-trained classifier: a second opinion on the marker-panel labels, independent of clustering.
# Downloads its model once. Pick a model that matches your tissue — a mismatched reference is confidently wrong.
import celltypist
from celltypist import models
model = {(P.get("celltypist_model") or "Immune_All_Low.pkl")!r}
models.download_models(model=[model], force_update=False)
pred = celltypist.annotate(adata, model=model, majority_voting=True, over_clustering="leiden")
adata.obs["cell_type"] = pred.predicted_labels["majority_voting"].astype(str)
sc.pl.umap(adata, color="cell_type", legend_loc="on data", legend_fontsize=6, show=False, save="_celltypist.png")
pd.crosstab(adata.obs["leiden"], adata.obs["cell_type"]).to_csv("celltypist_vs_leiden.csv")
'''
    if P.get("pathways") or P.get("ccc"):
        s += '''
# CellTypist labels when it ran, Leiden clusters otherwise
LABEL = "cell_type" if "cell_type" in adata.obs else "leiden"
'''
    if P.get("pathways"):
        s += f'''
# ------------------------------------------------------------------ {n()}. pathway activity per population (PROGENy)
import decoupler as dc
organism = "mouse" if adata.var_names.str.match(r"^[A-Z][a-z]").mean() > .5 else "human"
progeny = dc.op.progeny(organism=organism, top=500)
dc.mt.ulm(data=adata, net=progeny, tmin=5)           # writes adata.obsm["score_ulm"]
acts = dc.pp.get_obsm(adata, "score_ulm")
mean_by = pd.DataFrame(acts.X, index=adata.obs_names, columns=acts.var_names).groupby(
    adata.obs[LABEL].values, observed=True).mean()
import seaborn as sns
sns.clustermap(mean_by, cmap="RdBu_r", center=0, z_score=1, figsize=(7, 5)).savefig("progeny_by_population.png", dpi=200)
mean_by.to_csv("progeny_by_population.csv")
'''
    if P.get("trajectory"):
        root = P.get("root_cluster")
        s += f'''
# ------------------------------------------------------------------ {n()}. trajectory: PAGA + diffusion pseudotime
# PAGA summarizes which clusters are connected in the neighbour graph; DPT orders cells along it.
# Only meaningful if these populations really are a continuum — it will draw a path through anything.
sc.tl.paga(adata, groups="leiden")
sc.pl.paga(adata, threshold=.05, show=False, save="_paga.png")
sc.tl.diffmap(adata)
root = {root!r} or adata.obs["leiden"].value_counts().idxmax()
adata.uns["iroot"] = int(np.flatnonzero((adata.obs["leiden"] == str(root)).values)[0])
sc.tl.dpt(adata)
sc.pl.umap(adata, color=["leiden", "dpt_pseudotime"], show=False, save="_pseudotime.png")
'''
    if P.get("ccc"):
        s += f'''
# ------------------------------------------------------------------ {n()}. cell-cell communication (LIANA)
# Scores ligand-receptor pairs between populations from co-expression. A hypothesis about signalling,
# not evidence of it: the two populations must also be in contact in the tissue.
import liana as li
li.mt.rank_aggregate(adata, groupby=LABEL, expr_prop=.1, use_raw=False, verbose=False)
lr = adata.uns["liana_res"]
lr.sort_values("magnitude_rank").to_csv("ligand_receptor.csv", index=False)
li.pl.dotplot(adata, colour="magnitude_rank", size="specificity_rank", inverse_colour=True,
              inverse_size=True, top_n=20, orderby="magnitude_rank", orderby_ascending=True,
              figure_size=(9, 7)).save("ligand_receptor.png")
'''
    if P.get("gsea", True) and pb:
        s += f'''
# ------------------------------------------------------------------ {n()}. GSEA on the pseudobulk comparison
import gseapy as gp
rnk = ds.results_df.dropna(subset=["stat"])["stat"].sort_values(ascending=False)
rnk.index = rnk.index.astype(str)
rnk = rnk[~rnk.index.duplicated()]
pre = gp.prerank(rnk=rnk, gene_sets="MSigDB_Hallmark_2020", permutation_num=1000, min_size=15,
                 max_size=500, threads=4, seed=0, outdir=None, no_plot=True, verbose=False)
pre.res2d.sort_values("FDR q-val").to_csv("gsea_pseudobulk.csv", index=False)
'''
    return s
